
fit_params = {}


# Defines the model
[model]
    name = "model"
    module = "lightgbm.sklearn"
    class = "LGBMClassifier"
    params = {}


# Defines different preprocessing steps for different subsets of features
[[preprocessing]]
    # subset of features
    # Empty list IS allowed if we don't want to apply to any features.
    features = [
        "C17",
        "C14"]

    # Different preprocessing to apply to this subset
    [[preprocessing.steps]]
        name = "oe"
        module = "sklearn.preprocessing"
        class = "OrdinalEncoder"
        params = {}

    # We can add arbitrary number of steps
    #[[preprocessing.steps]]
    #    name = "imputer"
    #    module = "sklearn.preprocessing"
    #    class = "SimpleImputer"
    #    params = {}




